---
apiVersion: v1
kind: Service
metadata:
  name:  urlcollector-service-service
  namespace: default
  labels:
    app: urlcollector-service
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: urlcollector-service
    tier: compute

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: urlcollector-service-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: urlcollector-service
        tier: compute
    spec:
      containers:
      - image: registry.ng.bluemix.net/mhbraz/url-collector-service:latest
        imagePullPolicy: Always
        name: url-collector-container
        ports:
            - containerPort: 8080
      restartPolicy: Always